from constants import ESCAPE, text_colours, DOUBLE_HEIGHT, \
    mosaic_colours, SET_BACKGROUND

mode = "w+"
subpage = 1


page_title = config["page_title"] + " " + "{:02d}".format(subpage)
logo_spacer = " " * (39 - (4 + len(page_title) + 8))
with open(config['tti_path'] + "P" + str(config["page_number"]) + ".tti", mode) as file:
    if mode == "w+":
        file.write("DE,Autogenerated by Teletext-Twitter\r\n")
        file.write("SC,0000\r\n")
        file.write("PS,8000\r\n")
        file.write("CT," + str(config["cycle_time"]) + ",T\r\n")
        file.write("PN," + str(config["page_number"]) + "{:02}\r\n".format(subpage))
        file.write("OL,1," + ESCAPE + chr(text_colours[config["header_colour"]]) + SET_BACKGROUND +
            DOUBLE_HEIGHT + ESCAPE + chr(text_colours["white"]) +
            page_title + logo_spacer + ESCAPE + chr(mosaic_colours["cyan"]) + "\r\n")
        file.write("OL,3," + ESCAPE + chr(mosaic_colours[config["header_separator"]]) + (chr(35) * 39) + "\r\n")
        file.write("OL,4," + ESCAPE + chr(text_colours['red']) + "This is a test" + (" " * 25) + "\r\n")
